### ISSUE TITLE
v5.50.3 does not work with the Braze Android SDK v24

### ISSUE THREAD

**Issue by techouse** [mparticle-integrations/mparticle-android-integration-appboy#117]
The Braze Android SDK v24 replaced the `com.appboy` classpath with `com.braze` as [outlined in the changelog](https://github.com/Appboy/appboy-android-sdk/commit/443b232c545d5127bca0cd36001b5b421385a119)

The mParticle kit still looks for `com.appboy` and crashes the app.

```
D/mParticle(20290): Initializing kit: Appboy
D/AndroidRuntime(20290): Shutting down VM
E/AndroidRuntime(20290): FATAL EXCEPTION: main
E/AndroidRuntime(20290): Process: com.techouse.my_app, PID: 20290
E/AndroidRuntime(20290): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/appboy/enums/SdkFlavor;
E/AndroidRuntime(20290): 	at com.mparticle.kits.AppboyKit.onKitCreate(AppboyKit.kt:80)
E/AndroidRuntime(20290): 	at com.mparticle.kits.KitManagerImpl.initializeKit(KitManagerImpl.java:266)
E/AndroidRuntime(20290): 	at com.mparticle.kits.KitManagerImpl.configureKits(KitManagerImpl.java:226)
E/AndroidRuntime(20290): 	at com.mparticle.kits.KitManagerImpl.lambda$updateKits$0$com-mparticle-kits-KitManagerImpl(KitManagerImpl.java:157)
E/AndroidRuntime(20290): 	at com.mparticle.kits.KitManagerImpl$$ExternalSyntheticLambda0.run(Unknown Source:4)
E/AndroidRuntime(20290): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(20290): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(20290): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(20290): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(20290): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(20290): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20290): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(20290): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(20290): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.appboy.enums.SdkFlavor" on path: DexPathList[[zip file "/data/app/~~ccStR1eapguIw-VXvMb47w==/com.techouse.my_app-AxkrtUoUoXXCgDO8ZrkScg==/base.apk"],nativeLibraryDirectories=[/data/app/~~ccStR1eapguIw-VXvMb47w==/com.techouse.my_app-AxkrtUoUoXXCgDO8ZrkScg==/lib/arm64, /data/app/~~ccStR1eapguIw-VXvMb47w==/com.techouse.my_app-AxkrtUoUoXXCgDO8ZrkScg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(20290): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime(20290): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(20290): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(20290): 	... 13 more
```

It works fine with the Braze Android SDK v23.

This PR https://github.com/mparticle-integrations/mparticle-android-integration-appboy/pull/123 might fix this.

**Comment by techouse** [comment]
**v5.49.1** also doesn't work with Braze SDK v24.

**Comment by techouse** [comment]
**v5.50.3** also doesn't work with Braze SDK v24.
