### ISSUE TITLE
Increase amount of ANRs 

### ISSUE THREAD

**Issue by ateek** [mparticle-integrations/mparticle-android-integration-appboy#138]
we are facing an increasing amount of ANRs, for two weeks. nothing really changed in our Implementation, than introducing a new library Growthbook for FeatureFlagging

all the exceptions are coming from mParticle/Braze
here an example of the exception 
```
main (timed waiting):tid=1 systid=29577 
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:88)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(Builders.kt)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(Builders.kt)
       at com.braze.Braze.runForResult(SourceFile:5)
       at com.braze.Braze.getCurrentUser(SourceFile:1)
       at com.mparticle.kits.AppboyKit.logEvent(AppboyKit.kt:130)
       at com.mparticle.kits.KitManagerImpl.logMPEvent(KitManagerImpl.java:839)
       at com.mparticle.kits.KitManagerImpl.logEvent(KitManagerImpl.java:428)
       at com.mparticle.internal.d.e(SourceFile:23)
       at com.mparticle.internal.d.d(SourceFile:1)
       at com.mparticle.internal.d.a(SourceFile:9)
       at com.mparticle.internal.d.a(SourceFile:52)
       at com.mparticle.internal.KitsLoadedCallback.setKitsLoaded(SourceFile:4)
       at com.mparticle.kits.KitManagerImpl.lambda$updateKits$0(KitManagerImpl.java:158)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by Mansi-mParticle** [comment]
@ateek Sorry for the delay,Thanks for reporting this issue. Based on the stack trace, the ANRs are happening because the Braze SDK is calling a blocking API (runBlocking) on the main thread through the mParticle Appboy integration. This causes the main thread to freeze long enough to trigger an ANR.
To help us investigate further, could you share the following?

- Braze SDK version
- mParticle SDK version
- How Growthbook is initialized (main thread or background?)
- Whether this occurs during app startup or during specific events
- Whether you can reproduce this on any device/emulator

Once we have this information, we can debug the issue more accurately. Let me know if you need anything on my end!
